### ISSUE TITLE
incorporate luts into mapfile or otherwise

### ISSUE THREAD

**Issue by burningsage** [emerald-geomodelling/disco-tif#4]

**Comment by eddjharrison** [comment]
@burningsage make your notes

**Comment by burningsage** [comment]
look-up-tables (LUT) do work in a map file but only under some fairly strict circumstances. 
  1) LUTs only work on positive data ranges.  Specifically they are designed for uint8 data.  - To effectively use these the data need to me pre-mapped to uint8 data (i.e. min at 0, max at 255)
  2) a mapfile can only use 1 LUT set (either rgb(a) as 1 file or as 3(4) files). This means that you canNOT use one 
LUT to map the data data to 0:255 range and a second LUT to color it. 
      - ok, this isn't strictly true, but you would need to do this in multiple layers within the mapfile. Like the first layer would map the data to uint8 values, the second layer would map the first layer output to color. IFF disk space is an issue later, I suggest we revisit this thread.
  3) These limitations mean that you cannot use a LUT to map elevation data values to colors without further development.

Disco-tif will still write these files if directed to. A "set" of luts will 1) map the data to to rgba, 2) map data to uint8, 3) map uint8 data to r, g, b, a files, and 4) map uint8 data to a rgba file. I foresee this as minimizing the future development on this issues to only writing a new mapfile.

Since the export LUT file that is QGIS (maybe esri) compatible works and is slightly separate from the luts I will make this a separate function and sort of divorce it from the LUT bit

**Comment by eddjharrison** [comment]
[like]  Ed Harrison reacted to your message:
________________________________
